"""Approved local auto-coding state generated by NovaControl.

This module is written only after the user approves a temporary preview.
"""

from __future__ import annotations


APPROVED_GOAL = 'build a new tab for improve novacontrol'


def approved_goal() -> str:
    return APPROVED_GOAL


def approved_summary() -> str:
    return f"Approved auto-coding goal: {APPROVED_GOAL}"
