"""Helper functions and classes extracted from application.py."""

from __future__ import annotations

import re
from collections.abc import Mapping
from typing import Any

from novacontrol.core.security import ApprovalDecision, ApprovalRequest
from novacontrol.self_improvement import CodeChange


class ApprovedApprovalGateway:
    """Approval gateway that approves all requests (for web UI approval flow)."""

    async def request_approval(self, request: ApprovalRequest) -> ApprovalDecision:
        return ApprovalDecision(request.id, approved=True, decided_by="web.approval")


def build_auto_code_changes(goal: str) -> tuple[CodeChange, ...]:
    """Build auto code changes for the given goal."""
    clean_goal = " ".join(goal.strip().split()) or "Improve NovaControl"
    goal_literal = ascii(clean_goal[:500])
    module_content = (
        '"""Approved local auto-coding state generated by NovaControl.\n\n'
        "This module is written only after the user approves a temporary preview.\n"
        '"""\n\n'
        "from __future__ import annotations\n\n\n"
        f"APPROVED_GOAL = {goal_literal}\n\n\n"
        "def approved_goal() -> str:\n"
        "    return APPROVED_GOAL\n\n\n"
        "def approved_summary() -> str:\n"
        '    return f"Approved auto-coding goal: {APPROVED_GOAL}"\n'
    )
    test_content = (
        "from __future__ import annotations\n\n"
        "import unittest\n\n"
        "from novacontrol.self_improvement.local_autocode import approved_goal, approved_summary\n\n\n"
        "class LocalAutoCodeTests(unittest.TestCase):\n"
        "    def test_approved_goal_is_available(self) -> None:\n"
        "        self.assertTrue(approved_goal())\n"
        "        self.assertIn(approved_goal(), approved_summary())\n\n\n"
        'if __name__ == "__main__":\n'
        "    unittest.main()\n"
    )
    return (
        CodeChange(
            "src/novacontrol/self_improvement/local_autocode.py",
            module_content,
            "Record the approved auto-coding goal in a small importable module.",
        ),
        CodeChange(
            "tests/test_local_autocode.py",
            test_content,
            "Add a regression test proving the approved auto-coding module imports and reports the goal.",
        ),
    )


def verify_code_changes(changes: tuple[CodeChange, ...]) -> dict[str, Any]:
    """Verify code changes by checking syntax."""
    checks: list[dict[str, Any]] = []
    for change in changes:
        try:
            compile(change.content, change.relative_path, "exec")
            checks.append({"path": change.relative_path, "ok": True, "message": "syntax ok"})
        except SyntaxError as exc:
            checks.append({"path": change.relative_path, "ok": False, "message": exc.msg})
    return {"ok": all(check["ok"] for check in checks), "checks": checks}


def build_preview_payload(
    preview_id: str,
    changes: tuple[CodeChange, ...],
    verification: dict[str, Any],
) -> dict[str, Any]:
    """Build the preview payload for the improvement workflow."""
    return {
        "id": preview_id,
        "temporary": True,
        "change_count": len(changes),
        "verification": verification,
        "changes": [
            {
                "id": change.id,
                "relative_path": change.relative_path,
                "description": change.description,
                "content_preview": change.content.splitlines()[:8],
            }
            for change in changes
        ],
    }


_BROWSER_NAVIGATE_RE = re.compile(
    r"^(?:navigate\s+to|go\s+to|visit|browse\s+to|take\s+me\s+to|"
    r"open\s+the\s+website|open\s+website|open\s+the\s+site|open\s+site|open)\s+(.+)$"
)
_TRAILING_NOISE = re.compile(
    r"\s*(?:please|for me|now|in\s+(?:the\s+|my\s+)?browser|"
    r"on\s+(?:the\s+|my\s+)?browser|web\s+page|website|site|page|url)\s*$"
)


def resolve_browser_url(target: str) -> str:
    """Normalize a browser target to an absolute http(s) URL."""
    cleaned = target.strip().strip("\"'.,;!?")
    lower = cleaned.lower()
    if lower.startswith(("http://", "https://")):
        return cleaned
    # Bare host: example.com, sub.example.com:8080, or localhost[:port].
    if re.match(r"^(?:[a-z0-9-]+\.)+[a-z]{2,}(?::\d+)?$", lower) or re.match(r"^localhost(?::\d+)?$", lower):
        return "https://" + cleaned
    return cleaned


def _strip_target_noise(target: str) -> str:
    """Remove trailing conversational fillers from a parsed command target."""
    previous = None
    while previous != target:
        previous = target
        target = _TRAILING_NOISE.sub("", target)
    return target.strip()


def parse_browser_command(command: str) -> list[dict[str, Any]]:
    """Parse a natural language browser command into a list of actions.

    Returns a list of {"action": type, "target": url, "fields": {...}} dicts.
    Examples:
        "navigate to example.com" -> [{"action": "navigate", "target": "https://example.com"}]
        "open example.com website" -> [{"action": "navigate", "target": "https://example.com"}]
        "fill the form at https://example.com/login with username=admin, password=secret"
            -> [{"action": "fill_form", "target": "https://example.com/login",
                "fields": {"username": "admin", "password": "secret"}}]
    """
    lower = command.lower().strip()
    if not lower:
        return []

    # --- Fill a form at <url> with <selector>=<value> pairs ---
    fill_match = re.match(r"(?:fill|complete|submit)\s+(?:out|in)?\s*(?:the\s+)?form\s+(?:at|on)\s+", lower)
    if fill_match:
        rest = lower[fill_match.end():].strip()
        fields: dict[str, str] = {}
        if " with " in rest:
            url_part, _, after_with = rest.partition(" with ")
            for pair in re.split(r"\s*,\s*|\s+and\s+", after_with.strip()):
                key_value = re.match(r"(.+?)\s*[=:]\s*(.+)", pair.strip())
                if key_value:
                    fields[key_value.group(1).strip().strip('"')] = key_value.group(2).strip().strip('"')
        else:
            url_part = rest.split(",")[0].strip()
        target = resolve_browser_url(url_part)
        if target:
            return [{"action": "fill_form", "target": target, "fields": fields}]
        return []

    # --- Navigate to a website ---
    nav_match = _BROWSER_NAVIGATE_RE.match(lower)
    if nav_match:
        target = resolve_browser_url(_strip_target_noise(nav_match.group(1)))
        if target:
            return [{"action": "navigate", "target": target}]
    return []


def parse_desktop_command(command: str) -> list[dict[str, str]]:
    """Parse a natural language JARVIS command into a list of actions.

    Returns a list of {"action": type, "target": ..., "text": ...} dicts.
    Examples:
        "open notepad" -> [{"action": "open", "target": "notepad"}]
        "open notepad and type hello world" -> [{"action": "open", "target": "notepad"}, {"action": "type", "text": "hello world"}]
        "open folder C:\\Users" -> [{"action": "open_folder", "target": "C:\\Users"}]
        "open chrome and search for cats" -> [{"action": "open", "target": "chrome"}, {"action": "search", "text": "cats"}]
    """
    lower = command.lower().strip()
    actions: list[dict[str, str]] = []

    # Split on ' and ' to get sequential steps
    parts = re.split(r'\s+and\s+', lower, maxsplit=1)
    main_part = parts[0].strip()
    second_part = parts[1].strip() if len(parts) > 1 else None

    # --- Main action ---
    # Open folder
    folder_match = re.match(r'(?:open|show|go to|explore)\s+(?:folder|directory|dir|file explorer)\s+(.+)', main_part)
    if not folder_match:
        folder_match = re.match(r'(?:open|show|go to|explore)\s+([a-z]:\\.+|~/.+|/home/.+|/Users/.+)', main_part)
    if folder_match:
        actions.append({"action": "open_folder", "target": folder_match.group(1).strip()})
    else:
        # Open application
        app_match = re.match(r'(?:open|launch|start|run)\s+(.+)', main_part)
        if app_match:
            target = app_match.group(1).strip()
            # Clean up common phrases
            target = re.sub(r'\s*(please|for me|on my computer|on my laptop|on the computer)\s*$', '', target)
            if target:
                actions.append({"action": "open", "target": target})
        else:
            # Direct command — run as script
            actions.append({"action": "execute", "target": command})

    # --- Second action ---
    if second_part:
        type_match = re.match(r'(?:type|write|enter|input|put)\s+["\']?(.+?)["\']?\s*$', second_part)
        if type_match:
            actions.append({"action": "type", "text": type_match.group(1).strip()})
        else:
            search_match = re.match(r'(?:search|google|look up|find|browse)\s+(?:for\s+)?(.+)', second_part)
            if search_match:
                actions.append({"action": "search", "text": search_match.group(1).strip()})
            else:
                # Treat as additional type/text
                actions.append({"action": "type", "text": second_part})

    return actions or [{"action": "execute", "target": command}]


def resolve_phone_target(command: str) -> str:
    """Resolve a natural language phone command to a target application."""
    lower = command.lower().strip()
    for marker in (" on my phone", " on phone", " in my phone", " in phone", " phone"):
        lower = lower.replace(marker, "")
    for prefix in ("open ", "launch ", "run "):
        if lower.startswith(prefix):
            return command[len(prefix):].split(" on ", 1)[0].strip() or "requested app"
    for name in ("whatsapp", "chrome", "youtube", "gmail", "settings"):
        if name in lower:
            return name
    return command.strip() or "requested app"
