"""Helper functions and classes extracted from application.py."""

from __future__ import annotations

import re
from collections.abc import Mapping
from typing import Any
from urllib.parse import quote_plus

from novacontrol.core.security import ApprovalDecision, ApprovalRequest
from novacontrol.self_improvement import CodeChange


class ApprovedApprovalGateway:
    """Approval gateway that approves all requests (for web UI approval flow)."""

    async def request_approval(self, request: ApprovalRequest) -> ApprovalDecision:
        return ApprovalDecision(request.id, approved=True, decided_by="web.approval")


def build_auto_code_changes(goal: str) -> tuple[CodeChange, ...]:
    """Build auto code changes for the given goal."""
    clean_goal = " ".join(goal.strip().split()) or "Improve NovaControl"
    goal_literal = ascii(clean_goal[:500])
    module_content = (
        '"""Approved local auto-coding state generated by NovaControl.\n\n'
        "This module is written only after the user approves a temporary preview.\n"
        '"""\n\n'
        "from __future__ import annotations\n\n\n"
        f"APPROVED_GOAL = {goal_literal}\n\n\n"
        "def approved_goal() -> str:\n"
        "    return APPROVED_GOAL\n\n\n"
        "def approved_summary() -> str:\n"
        '    return f"Approved auto-coding goal: {APPROVED_GOAL}"\n'
    )
    test_content = (
        "from __future__ import annotations\n\n"
        "import unittest\n\n"
        "from novacontrol.self_improvement.local_autocode import approved_goal, approved_summary\n\n\n"
        "class LocalAutoCodeTests(unittest.TestCase):\n"
        "    def test_approved_goal_is_available(self) -> None:\n"
        "        self.assertTrue(approved_goal())\n"
        "        self.assertIn(approved_goal(), approved_summary())\n\n\n"
        'if __name__ == "__main__":\n'
        "    unittest.main()\n"
    )
    return (
        CodeChange(
            "src/novacontrol/self_improvement/local_autocode.py",
            module_content,
            "Record the approved auto-coding goal in a small importable module.",
        ),
        CodeChange(
            "tests/test_local_autocode.py",
            test_content,
            "Add a regression test proving the approved auto-coding module imports and reports the goal.",
        ),
    )


def verify_code_changes(changes: tuple[CodeChange, ...]) -> dict[str, Any]:
    """Verify code changes by checking syntax."""
    checks: list[dict[str, Any]] = []
    for change in changes:
        try:
            compile(change.content, change.relative_path, "exec")
            checks.append({"path": change.relative_path, "ok": True, "message": "syntax ok"})
        except SyntaxError as exc:
            checks.append({"path": change.relative_path, "ok": False, "message": exc.msg})
    return {"ok": all(check["ok"] for check in checks), "checks": checks}


def build_preview_payload(
    preview_id: str,
    changes: tuple[CodeChange, ...],
    verification: dict[str, Any],
) -> dict[str, Any]:
    """Build the preview payload for the improvement workflow."""
    return {
        "id": preview_id,
        "temporary": True,
        "change_count": len(changes),
        "verification": verification,
        "changes": [
            {
                "id": change.id,
                "relative_path": change.relative_path,
                "description": change.description,
                "content_preview": change.content.splitlines()[:8],
            }
            for change in changes
        ],
    }


_BROWSER_NAVIGATE_RE = re.compile(
    r"^(?:navigate\s+to|go\s+to|visit|browse\s+to|take\s+me\s+to|"
    r"open\s+the\s+website|open\s+website|open\s+the\s+site|open\s+site|open)\s+(.+)$"
)
_TRAILING_NOISE = re.compile(
    r"\s*(?:please|for me|now|in\s+(?:the\s+|my\s+)?browser|"
    r"on\s+(?:the\s+|my\s+)?browser|web\s+page|website|site|page|url)\s*$"
)

# Web-search phrasing, in order of specificity. Each pattern captures the query.
_WEB_SEARCH_PATTERNS = (
    re.compile(r"^(?:search|look\s+up)\s+(?:the\s+)?(?:web|internet)\s+(?:for|about)\s+(.+)$"),
    re.compile(r"^(?:web|internet)\s+search\s+(?:for\s+)?(.+)$"),
    re.compile(r"^(?:search|look\s+up)\s+for\s+(.+?)\s+on\s+(?:the\s+)?(?:web|internet)$"),
    re.compile(r"^google\s+(.+)$"),
)


def web_search_url(query: str) -> str:
    """Build the search-engine results URL for a query.

    DuckDuckGo's HTML endpoint serves a minimal, JS-free results page that is
    reliable to drive and inspect under automation (a JS-heavy engine page can
    hang or bot-gate a headless browser).
    """
    return "https://html.duckduckgo.com/html/?q=" + quote_plus(query.strip())


def resolve_browser_url(target: str) -> str:
    """Normalize a browser target to an absolute http(s) URL."""
    cleaned = target.strip().strip("\"'.,;!?")
    lower = cleaned.lower()
    if lower.startswith(("http://", "https://")):
        return cleaned
    # Bare host: example.com, sub.example.com:8080, or localhost[:port].
    if re.match(r"^(?:[a-z0-9-]+\.)+[a-z]{2,}(?::\d+)?$", lower) or re.match(r"^localhost(?::\d+)?$", lower):
        return "https://" + cleaned
    return cleaned


def _strip_target_noise(target: str) -> str:
    """Remove trailing conversational fillers from a parsed command target."""
    previous = None
    while previous != target:
        previous = target
        target = _TRAILING_NOISE.sub("", target)
    return target.strip()


def parse_browser_command(command: str) -> list[dict[str, Any]]:
    """Parse a natural language browser command into a list of actions.

    Returns a list of {"action": type, "target": url, "fields": {...}} dicts.
    Examples:
        "navigate to example.com" -> [{"action": "navigate", "target": "https://example.com"}]
        "open example.com website" -> [{"action": "navigate", "target": "https://example.com"}]
        "fill the form at https://example.com/login with username=admin, password=secret"
            -> [{"action": "fill_form", "target": "https://example.com/login",
                "fields": {"username": "admin", "password": "secret"}}]
        "search the web for quantum computing"
            -> [{"action": "search", "target": "https://html.duckduckgo.com/html/?q=quantum+computing",
                "query": "quantum computing"}]
    """
    lower = command.lower().strip()
    if not lower:
        return []

    # --- Fill a form at <url> with <selector>=<value> pairs ---
    fill_match = re.match(r"(?:fill|complete|submit)\s+(?:out|in)?\s*(?:the\s+)?form\s+(?:at|on)\s+", lower)
    if fill_match:
        rest = lower[fill_match.end():].strip()
        fields: dict[str, str] = {}
        if " with " in rest:
            url_part, _, after_with = rest.partition(" with ")
            for pair in re.split(r"\s*,\s*|\s+and\s+", after_with.strip()):
                key_value = re.match(r"(.+?)\s*[=:]\s*(.+)", pair.strip())
                if key_value:
                    fields[key_value.group(1).strip().strip('"')] = key_value.group(2).strip().strip('"')
        else:
            url_part = rest.split(",")[0].strip()
        target = resolve_browser_url(url_part)
        if target:
            return [{"action": "fill_form", "target": target, "fields": fields}]
        return []

    # --- Search the web in a browser (a real engine results page) ---
    for pattern in _WEB_SEARCH_PATTERNS:
        match = pattern.match(lower)
        if not match:
            continue
        query = _strip_target_noise(match.group(1))
        if query:
            return [{"action": "search", "target": web_search_url(query), "query": query}]
        return []

    # --- Navigate to a website ---
    nav_match = _BROWSER_NAVIGATE_RE.match(lower)
    if nav_match:
        target = resolve_browser_url(_strip_target_noise(nav_match.group(1)))
        if target:
            return [{"action": "navigate", "target": target}]
    return []


def parse_phone_command(command: str) -> tuple[str, str]:
    """Classify a phone command into (kind, argument).

    Kind is one of "open" (arg = app), "text" (arg = message spec without the
    verb/phone markers, parsed further by the controller), "call" (arg =
    contact), or "screenshot" (arg = ""). Device markers are stripped
    case-insensitively from the ORIGINAL so arguments keep their case.
    "open" remains the fallback so unknown verbs keep the old behavior.
    """
    stripped = re.sub(
        r"\s+(?:on\s+(?:my|the)\s+phone|on\s+phone|in\s+(?:my\s+)?phone|\s*phone)\b",
        "",
        command.strip(),
        flags=re.IGNORECASE,
    ).strip()
    lower = " ".join(stripped.lower().split())
    for verb in ("text", "sms", "message"):
        if lower.startswith(f"{verb} "):
            return "text", stripped[len(verb) + 1:].strip()
    if "screenshot" in lower:
        return "screenshot", ""
    for verb in ("call ", "dial "):
        if lower.startswith(verb):
            return "call", stripped[len(verb) - 1:].strip()
    for prefix in ("open ", "launch ", "run "):
        if lower.startswith(prefix):
            return "open", stripped[len(prefix):].split(" on ", 1)[0].strip() or "requested app"
    for name in ("whatsapp", "chrome", "youtube", "gmail", "settings"):
        if name in lower:
            return "open", name
    return "open", stripped or "requested app"


def resolve_phone_target(command: str) -> str:
    """Resolve a natural language phone command to a target application.

    Kept for callers that only need the app target of an open-application
    command; plan_phone_command uses parse_phone_command for full coverage.
    """
    kind, argument = parse_phone_command(command)
    if kind == "open":
        return argument
    return argument or command.strip() or "requested app"
